# Copyright 2020 QubiQ
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Monolitic Sales",
    "summary": "Monolitic module for Sales",
    "version": "14.0.1.0.1",
    "category": "Sales",
    "website": "https://www.qubiq.es",
    "author": "QubiQ",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {
        "python": [],
        "bin": [],
    },
    "depends": [
        "account",
        "account_payment_return",
        "sale_crm",
        "sale_cancel_reason",
        "sale_order_line_date",
        "sale_order_line_menu",
        "mail",
        "monolitic_crm",
        "monolitic_stock",
        "monolitic_hr_custom",
        "monolitic_product",
        "web_notify",
    ],
    "data": [
        "data/automatic_invoicing_ir_cron.xml",
        "data/product_data.xml",
        "data/sale_groups.xml",
        "reports/invoice_document_custom.xml",
        "reports/sale_order_document_custom.xml",
        "reports/sale_order_report_layout.xml",
        "reports/sale_order_proforma_report.xml",
        "views/account_invoice_view.xml",
        "views/account_invoice_line.xml",
        "views/account_payment_term_view.xml",
        "views/commercial_monthly_amount_view.xml",
        "views/commercial_target_coeficient_view.xml",
        "views/commercial_target_view.xml",
        "views/commercial_zone_view.xml",
        "views/crm_lead_view.xml",
        "views/crm_stage_view.xml",
        "views/customer_prevision_view.xml",
        "views/res_country_state_view.xml",
        "views/res_users_view.xml",
        "views/sale_order.xml",
        "views/sale_order_line.xml",
        "views/sale_report.xml",
        "views/stock_picking_view.xml",
        "views/sale_views.xml",
        "wizards/mass_edit_commercial_wizard.xml",
        "wizards/commercial_target.xml",
        "wizards/customer_prevision.xml",
        "data/res.groups.xml",
        "views/res_partner.xml",
        "security/ir.model.access.csv",
        "data/ir.rule.xml",
    ],
}
