from . import notes_rma
from . import account_analytic_line
from . import crm_claim_ept_line
from . import crm_claim_ept
from . import account_invoice
from . import stock_picking
from . import stock_warehouse
from . import stock_move
from . import sale_order
from . import res_partner
