# Copyright 2019 Xavier Jimenez <xavier.jimenez@qubiq.es>
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
{
    "name": "Monolitic Stock",
    "summary": "Monolitic Stock custom",
    "version": "14.0.1.0.1",
    "category": "Stock",
    "website": "https://www.qubiq.es",
    "author": "QubiQ",
    "license": "AGPL-3",
    "application": False,
    "installable": True,
    "external_dependencies": {
        "python": [],
        "bin": [],
    },
    "depends": [
        "monolitic_base",
        "monolitic_product_expenses",
        "delivery",
        "sale_stock",
        "purchase",
        "product_supplierinfo_for_customer",
        "web",
        "stock_barcode",
        "l10n_es_dua_sii",
    ],
    "data": [
        "data/stock_quant_historic.xml",
        "reports/external_layout.xml",
        "reports/customer_label_report.xml",
        "reports/paper_format.xml",
        "reports/paperformat_warranty.xml",
        "reports/product_report_labels.xml",
        "reports/product_label_report_wizard.xml",
        "reports/stock_picking_report_label.xml",
        "reports/report_warranty.xml",
        "reports/reports.xml",
        "reports/stock_inventory.xml",
        "reports/stock_picking_wo_manufacturing.xml",
        "reports/stock_picking.xml",
        "wizards/csv_export_wizard.xml",
        "wizards/product_label_wizard.xml",
        "views/stock_picking.xml",
        "views/product_template.xml",
        "views/sale_order.xml",
        "views/res_config_settings.xml",
        "views/res_partner.xml",
        "views/stock_inventory.xml",
        "views/stock_move.xml",
        "views/stock_quant.xml",
        "views/stock_picking.xml",
        "views/stock_warehouse_orderpoint.xml",
        "views/stock_orderpoint_reservation.xml",
        "views/stock_delivery_condition_view.xml",
        "data/res.groups.xml",
        "security/ir.model.access.csv",
    ],
}
